name: PR Comment Bot

on:
  pull_request_target:
    types: [opened, reopened, synchronize, edited]

jobs:
  pr-bot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Detect Contributor.md change
        id: filecheck
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            const files = await github.rest.pulls.listFiles({ owner, repo, pull_number, per_page: 100 });
            const changed = files.data.some(f => /contributor\.md/i.test(f.filename));
            core.setOutput('fileChanged', changed ? 'true' : 'false');

      - name: Run PR bot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./.github/scripts/pr-bot.js');
            await script({
              github,
              context,
              fileChanged: '${{ steps.filecheck.outputs.fileChanged }}'
            });